name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: meetjoaostein/github-changelog-generator@v8.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: true
          name-template: v$NEXT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body_path: .github/changelog.md
